CATEGORIES = {
    "Database Design and Normalization": "https://www.w3resource.com/sql-exercises/sql-database-design-and-normalization_index.php",
    "Data Definition Language": "https://www.w3resource.com/sql-exercises/sql-data-definition-language-exercises_index.php",
    "Data Manipulation Language": "https://www.w3resource.com/sql-exercises/sql-data-manipulation-language-exercises_index.php",
    "Performance Tuning and Optimization": "https://www.w3resource.com/sql-exercises/sql-performance-tuning-and-optimization-exercises_index.php",
    "Retrieve data from tables": "https://www.w3resource.com/sql-exercises/sql-retrieve-from-table.php",
    "Boolean and Relational Operators": "https://www.w3resource.com/sql-exercises/sql-boolean-operators.php",
    "Wildcard and Special operators": "https://www.w3resource.com/sql-exercises/sql-wildcard-special-operators.php",
    "Aggregate Functions": "https://www.w3resource.com/sql-exercises/sql-aggregate-functions.php",
    "Formatting query output": "https://www.w3resource.com/sql-exercises/sql-fromatting-output-exercises.php",
    "Query on Multiple Tables": "https://www.w3resource.com/sql-exercises/sql-exercises-quering-on-multiple-table.php",
    "Error Handling and Debugging": "https://www.w3resource.com/sql-exercises/sql-error-handling-and-debugging_index.php",
    "Security and Access Control": "https://www.w3resource.com/sql-exercises/sql-security-and-access-control_index.php",
    "Temporal Tables and Versioning": "https://www.w3resource.com/sql-exercises/sql-temporal-tables-and-versioning_index.php",
    "Database Backup and Recovery": "https://www.w3resource.com/sql-exercises/sql-database-backup-and-recovery-temporal-tables-and-versioning_index.php",
    "Cross-Platform": "https://www.w3resource.com/sql-exercises/cross-platform-sql-exercises_index.php",
    "Advanced SQL Features": "https://www.w3resource.com/sql-exercises/sql-advanced-SQL-features-exercises_index.php",
    "SQL JOINS": "https://www.w3resource.com/sql-exercises/sql-joins-exercises.php",
    "SUBQUERIES": "https://www.w3resource.com/sql-exercises/subqueries/index.php",
    "FILTERING and SORTING on HR Database": "https://www.w3resource.com/sql-exercises/sorting-and-filtering-hr/index.php",
    "Transactions and Concurrency Control": "https://www.w3resource.com/sql-exercises/sql-transactions-and-concurrency-control_index.php",
    "Stored Procedures and Functions": "https://www.w3resource.com/sql-exercises/sql-stored-procedures-and-functions-exercises_index.php",
    "SUBQUERIES on HR Database": "https://www.w3resource.com/sql-exercises/sql-subqueries-exercises.php",
    "JOINS on HR Database": "https://www.w3resource.com/sql-exercises/joins-hr/index.php",
    "SQL UNION": "https://www.w3resource.com/sql-exercises/union/sql-union.php",
    "SQL VIEW": "https://www.w3resource.com/sql-exercises/view/sql-view.php",
    "SQL User Management": "https://www.w3resource.com/sql-exercises/sql-user-management.php",
    "Movie DB - BASIC": "https://www.w3resource.com/sql-exercises/movie-database-exercise/basic-exercises-on-movie-database.php",
    "Movie DB - SUBQUERIES": "https://www.w3resource.com/sql-exercises/movie-database-exercise/subqueries-exercises-on-movie-database.php",
    "Movie DB - JOINS": "https://www.w3resource.com/sql-exercises/movie-database-exercise/joins-exercises-on-movie-database.php",
    "Soccer DB - BASIC": "https://www.w3resource.com/sql-exercises/soccer-database-exercise/basic-exercises-on-soccer-database.php",
    "Soccer DB - SUBQUERIES": "https://www.w3resource.com/sql-exercises/soccer-database-exercise/subqueries-exercises-on-soccer-database.php",
    "Soccer DB - JOINS": "https://www.w3resource.com/sql-exercises/soccer-database-exercise/joins-exercises-on-soccer-database.php",
    "Hospital DB": "https://www.w3resource.com/sql-exercises/hospital-database-exercise/sql-exercise-on-hospital-database.php",
    "Employee DB - BASIC": "https://www.w3resource.com/sql-exercises/employee-database-exercise/index.php",
    "Employee DB - SUBQUERIES": "https://www.w3resource.com/sql-exercises/employee-database-exercise/subqueries-exercises-on-employee-database.php",
    "AdventureWorks": "https://www.w3resource.com/sql-exercises/adventureworks/index.php",
    "SQL Challenges-1": "https://www.w3resource.com/sql-exercises/challenges-1/index.php",
    "SQL Challenges-2": "https://www.w3resource.com/sql-exercises/challenges-1/sql-25-query-challenges.php",
}
