print('kiroLLOS'.lower())
print('kiroLLOS'.upper())
print('abc'.islower())
print('abc'.isupper())
print('123'.isdecimal())

print('abcdef'.startswith('abc'))
print('abcdef'.startswith('abcD'))
print('abcdef'.endswith('def'))
print('abcdef'.find('abc'))
print('abcdef'.find('xx'))
print('abcdef'.rfind('bc'))
print('hihihi '.count('hi'))
print('AAAA'.count('AA'))
